/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AddressStatus = 'pendingAddressCompletion' | 'binRequested' | 'pendingBinPayment' | 'pendingBinDelivery' | 'binDelivered';

export const AddressStatus = {
    PendingAddressCompletion: 'pendingAddressCompletion' as AddressStatus,
    BinRequested: 'binRequested' as AddressStatus,
    PendingBinPayment: 'pendingBinPayment' as AddressStatus,
    PendingBinDelivery: 'pendingBinDelivery' as AddressStatus,
    BinDelivered: 'binDelivered' as AddressStatus
};

