/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AddressStatus = 0 | 1 | 2 | 3 | 4;

export const AddressStatus = {
    NUMBER_0: 0 as AddressStatus,
    NUMBER_1: 1 as AddressStatus,
    NUMBER_2: 2 as AddressStatus,
    NUMBER_3: 3 as AddressStatus,
    NUMBER_4: 4 as AddressStatus
};

