/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AddressStatus = 'PendingAddressCompletion' | 'BinRequested' | 'PendingBinPayment' | 'PendingBinDelivery' | 'BinDelivered';

export const AddressStatus = {
    PendingAddressCompletion: 'PendingAddressCompletion' as AddressStatus,
    BinRequested: 'BinRequested' as AddressStatus,
    PendingBinPayment: 'PendingBinPayment' as AddressStatus,
    PendingBinDelivery: 'PendingBinDelivery' as AddressStatus,
    BinDelivered: 'BinDelivered' as AddressStatus
};

