/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressSuggestion } from './addressSuggestion';
import { AddressStatus } from './addressStatus';


export interface CreateAddressCommand { 
    userId?: string;
    address?: AddressSuggestion;
    totalBins?: number;
    addressNotes?: string | null;
    status?: AddressStatus;
}
export namespace CreateAddressCommand {
}


