/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDriver {
    vehicleCapacity: number;
    licenseNumber: string | null;
    active: boolean;
    userId: string;
    homeAddressLabel: string | null;
    homeAddressLong: number;
    homeAddressLat: number;
    dropoffLocationLabel: string | null;
    dropoffLocationLong: number;
    dropoffLocationLat: number;
    timeZoneId: string;
}

