/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDriverCommand { 
    userId?: string;
    active?: boolean;
    licenseNumber?: string | null;
    homeAddressLabel?: string | null;
    homeAddressLong?: number;
    homeAddressLat?: number;
    dropoffLocationLabel?: string | null;
    dropoffLocationLong?: number;
    dropoffLocationLat?: number;
    vehicleCapacity?: number;
    timeZoneId?: string | null;
}

