/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressSuggestion } from './addressSuggestion';


export interface CustomerCreateAddressCommand { 
    address?: AddressSuggestion;
    totalBins?: number;
    addressNotes?: string | null;
}

