/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionJob } from './collectionJob';
import { DriverRoute } from './driverRoute';


export interface DailyOptimizationResult { 
    routes?: Array<DriverRoute> | null;
    unassignedJobs?: Array<CollectionJob> | null;
    totalDistanceMeters?: number;
    totalDurationSeconds?: number;
}

