/**
 * MySmartCloset API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type DayOfWeek =
  | 'monday'
  | 'tuesday'
  | 'wednesday'
  | 'thursday'
  | 'friday'
  | 'saturday'
  | 'sunday';

export const DayOfWeek = {
  Monday: 'monday' as DayOfWeek,
  Tuesday: 'tuesday' as DayOfWeek,
  Wednesday: 'wednesday' as DayOfWeek,
  Thursday: 'thursday' as DayOfWeek,
  Friday: 'friday' as DayOfWeek,
  Saturday: 'saturday' as DayOfWeek,
  Sunday: 'sunday' as DayOfWeek,
};
