/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DayOfWeek = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';

export const DayOfWeek = {
    Monday: 'Monday' as DayOfWeek,
    Tuesday: 'Tuesday' as DayOfWeek,
    Wednesday: 'Wednesday' as DayOfWeek,
    Thursday: 'Thursday' as DayOfWeek,
    Friday: 'Friday' as DayOfWeek,
    Saturday: 'Saturday' as DayOfWeek,
    Sunday: 'Sunday' as DayOfWeek
};

