/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RouteStop } from './routeStop';


export interface DriverRoute { 
    driverId?: string | null;
    stops?: Array<RouteStop> | null;
    totalDistanceMeters?: number | null;
    totalDurationSeconds?: number | null;
}

