/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Frequency = 'daily' | 'weekly' | 'biWeekly' | 'monthly' | 'yearly' | 'oneTime';

export const Frequency = {
    Daily: 'daily' as Frequency,
    Weekly: 'weekly' as Frequency,
    BiWeekly: 'biWeekly' as Frequency,
    Monthly: 'monthly' as Frequency,
    Yearly: 'yearly' as Frequency,
    OneTime: 'oneTime' as Frequency
};

