/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Frequency = 'Daily' | 'Weekly' | 'BiWeekly' | 'Monthly' | 'Yearly' | 'OneTime';

export const Frequency = {
    Daily: 'Daily' as Frequency,
    Weekly: 'Weekly' as Frequency,
    BiWeekly: 'BiWeekly' as Frequency,
    Monthly: 'Monthly' as Frequency,
    Yearly: 'Yearly' as Frequency,
    OneTime: 'OneTime' as Frequency
};

