/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Frequency = 0 | 1 | 2 | 3 | 4 | 5;

export const Frequency = {
    NUMBER_0: 0 as Frequency,
    NUMBER_1: 1 as Frequency,
    NUMBER_2: 2 as Frequency,
    NUMBER_3: 3 as Frequency,
    NUMBER_4: 4 as Frequency,
    NUMBER_5: 5 as Frequency
};

