/**
 * MySmartCloset API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressStatus } from './addressStatus';

export interface GetAddress {
  id: string;
  address: string | null;
  addressNotes: string | null;
  totalBins: number;
  addressStatus: AddressStatus;
}
export namespace GetAddress {}
