/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoles } from './userRoles';


export interface GetUser { 
    id: string;
    name: string | null;
    email: string | null;
    phoneNumber: string | null;
    role: UserRoles;
}
export namespace GetUser {
}


