/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MegabinWebSharedDomainEnumsDayOfWeek } from './megabinWebSharedDomainEnumsDayOfWeek';
import { MegabinWebSharedDomainEnumsFrequency } from './megabinWebSharedDomainEnumsFrequency';


export interface MegabinWebFeaturesAdminAddScheduleContractAddScheduleContractCommand { 
    addressId?: string;
    dayOfWeek?: MegabinWebSharedDomainEnumsDayOfWeek;
    frequency?: MegabinWebSharedDomainEnumsFrequency;
}
export namespace MegabinWebFeaturesAdminAddScheduleContractAddScheduleContractCommand {
}


