/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MegabinWebSharedDomainEnumsDayOfWeek } from './megabinWebSharedDomainEnumsDayOfWeek';
import { MegabinWebSharedDomainEnumsFrequency } from './megabinWebSharedDomainEnumsFrequency';


export interface MegabinWebFeaturesAdminUpdateScheduleContractUpdateScheduleContractCommand { 
    contractId?: string;
    frequency?: MegabinWebSharedDomainEnumsFrequency;
    dayOfWeek?: MegabinWebSharedDomainEnumsDayOfWeek;
    active?: boolean;
    approvedExternally?: boolean;
}
export namespace MegabinWebFeaturesAdminUpdateScheduleContractUpdateScheduleContractCommand {
}


