/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MegabinWebSharedDomainEnumsUserRoles } from './megabinWebSharedDomainEnumsUserRoles';


export interface MegabinWebFeaturesAdminUpdateUserUpdateUserCommand { 
    userId?: string;
    name?: string | null;
    email?: string | null;
    role?: MegabinWebSharedDomainEnumsUserRoles;
    phoneNumber?: string | null;
}
export namespace MegabinWebFeaturesAdminUpdateUserUpdateUserCommand {
}


