/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MegabinWebSharedDTOsRoutingLocation } from './megabinWebSharedDTOsRoutingLocation';
import { MegabinWebSharedDomainEnumsAddressStatus } from './megabinWebSharedDomainEnumsAddressStatus';


export interface MegabinWebSharedDTOsAddressesGetAddress { 
    id: string;
    address: string | null;
    addressNotes: string | null;
    totalBins: number;
    addressStatus: MegabinWebSharedDomainEnumsAddressStatus;
    location: MegabinWebSharedDTOsRoutingLocation;
}
export namespace MegabinWebSharedDTOsAddressesGetAddress {
}


