/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MegabinWebSharedDTOsRoutingLocation } from './megabinWebSharedDTOsRoutingLocation';
import { MegabinWebSharedDomainEnumsAddressStatus } from './megabinWebSharedDomainEnumsAddressStatus';


export interface MegabinWebFeaturesAdminUpdateUserAddressUpdateUserAddressCommand { 
    addressId?: string;
    totalBins?: number;
    addressNotes?: string | null;
    status?: MegabinWebSharedDomainEnumsAddressStatus;
    location?: MegabinWebSharedDTOsRoutingLocation;
}
export namespace MegabinWebFeaturesAdminUpdateUserAddressUpdateUserAddressCommand {
}


