/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MegabinWebSharedDomainEnumsAddressStatus = 'PendingAddressCompletion' | 'BinRequested' | 'PendingBinPayment' | 'PendingBinDelivery' | 'BinDelivered';

export const MegabinWebSharedDomainEnumsAddressStatus = {
    PendingAddressCompletion: 'PendingAddressCompletion' as MegabinWebSharedDomainEnumsAddressStatus,
    BinRequested: 'BinRequested' as MegabinWebSharedDomainEnumsAddressStatus,
    PendingBinPayment: 'PendingBinPayment' as MegabinWebSharedDomainEnumsAddressStatus,
    PendingBinDelivery: 'PendingBinDelivery' as MegabinWebSharedDomainEnumsAddressStatus,
    BinDelivered: 'BinDelivered' as MegabinWebSharedDomainEnumsAddressStatus
};

