/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MegabinWebSharedDomainEnumsUserRoles = 'Admin' | 'Driver' | 'Customer';

export const MegabinWebSharedDomainEnumsUserRoles = {
    Admin: 'Admin' as MegabinWebSharedDomainEnumsUserRoles,
    Driver: 'Driver' as MegabinWebSharedDomainEnumsUserRoles,
    Customer: 'Customer' as MegabinWebSharedDomainEnumsUserRoles
};

