/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MegabinWebSharedDomainEnumsDayOfWeek = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';

export const MegabinWebSharedDomainEnumsDayOfWeek = {
    Monday: 'Monday' as MegabinWebSharedDomainEnumsDayOfWeek,
    Tuesday: 'Tuesday' as MegabinWebSharedDomainEnumsDayOfWeek,
    Wednesday: 'Wednesday' as MegabinWebSharedDomainEnumsDayOfWeek,
    Thursday: 'Thursday' as MegabinWebSharedDomainEnumsDayOfWeek,
    Friday: 'Friday' as MegabinWebSharedDomainEnumsDayOfWeek,
    Saturday: 'Saturday' as MegabinWebSharedDomainEnumsDayOfWeek,
    Sunday: 'Sunday' as MegabinWebSharedDomainEnumsDayOfWeek
};

