/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MegabinWebSharedDTOsRoutingLocation } from './megabinWebSharedDTOsRoutingLocation';


export interface MegabinWebSharedDTOsRoutingAddressSuggestion { 
    label?: string | null;
    location?: MegabinWebSharedDTOsRoutingLocation;
    region?: string | null;
    locality?: string | null;
    country?: string | null;
}

