/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MegabinWebSharedDTOsRoutingAddressSuggestion } from './megabinWebSharedDTOsRoutingAddressSuggestion';
import { MegabinWebSharedDomainEnumsAddressStatus } from './megabinWebSharedDomainEnumsAddressStatus';


export interface MegabinWebFeaturesAddressCreateAddressCreateAddressCommand { 
    userId?: string;
    address?: MegabinWebSharedDTOsRoutingAddressSuggestion;
    totalBins?: number;
    addressNotes?: string | null;
    status?: MegabinWebSharedDomainEnumsAddressStatus;
}
export namespace MegabinWebFeaturesAddressCreateAddressCreateAddressCommand {
}


