/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MegabinWebSharedDomainEnumsFrequency = 'Daily' | 'Weekly' | 'BiWeekly' | 'Monthly' | 'Yearly' | 'OneTime';

export const MegabinWebSharedDomainEnumsFrequency = {
    Daily: 'Daily' as MegabinWebSharedDomainEnumsFrequency,
    Weekly: 'Weekly' as MegabinWebSharedDomainEnumsFrequency,
    BiWeekly: 'BiWeekly' as MegabinWebSharedDomainEnumsFrequency,
    Monthly: 'Monthly' as MegabinWebSharedDomainEnumsFrequency,
    Yearly: 'Yearly' as MegabinWebSharedDomainEnumsFrequency,
    OneTime: 'OneTime' as MegabinWebSharedDomainEnumsFrequency
};

