/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StopType } from './stopType';
import { Location } from './location';


export interface RouteStop { 
    type?: StopType;
    location?: Location;
    address?: string | null;
    jobId?: string | null;
}
export namespace RouteStop {
}


