/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DayOfWeek } from './dayOfWeek';
import { ScheduleContractPreviewDto } from './scheduleContractPreviewDto';


export interface RoutePreviewDto { 
    targetDate: string;
    dayOfWeek: DayOfWeek;
    activeDriverCount: number;
    existingCollectionsCount: number;
    scheduleContracts: Array<ScheduleContractPreviewDto> | null;
}
export namespace RoutePreviewDto {
}


