/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Frequency } from './frequency';


export interface ScheduleContractPreviewDto { 
    contractId: string;
    addressId: string;
    address: string | null;
    customerName: string | null;
    customerEmail: string | null;
    frequency: Frequency;
    totalBins: number;
}
export namespace ScheduleContractPreviewDto {
}


