/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StopType = 'Collection' | 'Depot';

export const StopType = {
    Collection: 'Collection' as StopType,
    Depot: 'Depot' as StopType
};

