/**
 * Megabin API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StopType = 'collection' | 'depot';

export const StopType = {
    Collection: 'collection' as StopType,
    Depot: 'depot' as StopType
};

