/**
 * MySmartCloset API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressStatus } from './addressStatus';

export interface UpdateAddress {
  addressId: string;
  totalBins: number;
  addressNotes?: string | null;
  status: AddressStatus;
}
export namespace UpdateAddress {}
