/**
 * MySmartCloset API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoles } from './userRoles';

export interface UpdateUser {
  userId: string;
  name: string | null;
  email: string | null;
  role: UserRoles;
  totalBins: number;
}
export namespace UpdateUser {}
