/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressStatus } from './addressStatus';
import { Location } from './location';


export interface UpdateUserAddressCommand { 
    addressId?: string;
    totalBins?: number;
    addressNotes?: string | null;
    status?: AddressStatus;
    location?: Location;
}
export namespace UpdateUserAddressCommand {
}


