/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRoles = 'Admin' | 'Driver' | 'Customer';

export const UserRoles = {
    Admin: 'Admin' as UserRoles,
    Driver: 'Driver' as UserRoles,
    Customer: 'Customer' as UserRoles
};

