/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRoles = 'admin' | 'driver' | 'customer';

export const UserRoles = {
    Admin: 'admin' as UserRoles,
    Driver: 'driver' as UserRoles,
    Customer: 'customer' as UserRoles
};

