/**
 * MySmartCloset API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRoles = 0 | 1 | 2;

export const UserRoles = {
    NUMBER_0: 0 as UserRoles,
    NUMBER_1: 1 as UserRoles,
    NUMBER_2: 2 as UserRoles
};

